DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS topics;
DROP TABLE IF EXISTS moderators_rights;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS forums;

CREATE TABLE forums (
	id BIGINT UNSIGNED AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	description TEXT NOT NULL,

	PRIMARY KEY(id)
) ENGINE InnoDB;

CREATE TABLE users (
	id BIGINT UNSIGNED AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	type SMALLINT UNSIGNED NOT NULL,
	location VARCHAR(255),
	language SMALLINT UNSIGNED NOT NULL,
	style SMALLINT UNSIGNED NOT NULL,

	PRIMARY KEY(id),
	UNIQUE(name),
	CHECK (type > 0 AND type < 4)
) ENGINE InnoDB;

CREATE TABLE moderators_rights (
	user_id BIGINT UNSIGNED NOT NULL,
	forum_id BIGINT UNSIGNED NOT NULL,

	UNIQUE(user_id, forum_id),
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
	FOREIGN KEY (forum_id) REFERENCES forums (id) ON DELETE CASCADE
) ENGINE InnoDB;

CREATE TABLE topics (
	id BIGINT UNSIGNED AUTO_INCREMENT,
	forum_id BIGINT UNSIGNED NOT NULL,
	poster_id BIGINT UNSIGNED NOT NULL,
	title VARCHAR(255) NOT NULL,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	views_count BIGINT UNSIGNED NOT NULL DEFAULT 0,

	PRIMARY KEY(id),
	FOREIGN KEY (forum_id) REFERENCES forums (id) ON DELETE CASCADE,
	FOREIGN KEY (poster_id) REFERENCES users (id) ON DELETE CASCADE	
) ENGINE InnoDB;

CREATE TABLE posts (
	id BIGINT UNSIGNED AUTO_INCREMENT,
	forum_id BIGINT UNSIGNED NOT NULL REFERENCES forums (id) ON DELETE CASCADE,
	topic_id BIGINT UNSIGNED NOT NULL REFERENCES topics (id) ON DELETE CASCADE,
	poster_id BIGINT UNSIGNED NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	content TEXT NOT NULL,
	is_textile BOOLEAN NOT NULL,
	posted_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	last_updated_time TIMESTAMP NOT NULL,

	PRIMARY KEY(id),
	FOREIGN KEY (forum_id) REFERENCES forums (id) ON DELETE CASCADE,
	FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE CASCADE,
	FOREIGN KEY (poster_id) REFERENCES users (id) ON DELETE CASCADE	
) ENGINE InnoDB;
